### ISSUE TITLE
Cache warmup fails if no database connectiion is setup

### ISSUE THREAD

**Issue by dmolineus** [terminal42/contao-url-rewrite#10]
I prepared the required packages in the composer.json for a new project. Installing the project fails during cache warmup because the rewrite bundle doesn't handle the case that no database connection is available (Related #6).

> An exception occurred in driver: SQLSTATE[HY000] [2002] No such file or directory in . (which is being imported from "@Terminal42UrlRewriteBundle/Resources/config/routing.yml"). Make sure there is a loader supporting the "terminal42_url_rewrite" type.

**Comment by qzminski** [comment]
@dmolineus can you please try to install `dev-hotfix/1.2.5`? If that works out I will release a new stable version.

**Comment by dmolineus** [comment]
Thanks. I tested composer update with the hotfix branch. Works now. Not tested any other stuff though.
