### ISSUE TITLE
Use RouterInterface instead of Router in the listener

### ISSUE THREAD

**Issue by Toflar** [terminal42/contao-url-rewrite#11]
Otherwise Contao 4.7 won't work due to `ChainRouter` being passed instead.

We might want to add more optimizations for Contao 4.7 because we're using Symfony CMF Routing now and we'll be able to add the routes dynamically instead of deleting and updating cache files but this is a quick fix to ensure compat I guess 😄

**Comment by leofeyer** [comment]
This is the exception (in case it helps):

`Argument 1 passed to Terminal42\UrlRewriteBundle\EventListener\RewriteContainerListener::__construct() must be an instance of Symfony\Bundle\FrameworkBundle\Routing\Router, instance of Symfony\Cmf\Component\Routing\ChainRouter given, called in …/var/cache/prod/ContainerFDpN0DW/getTerminal42UrlRewrite_Listener_RewriteContainerService.php on line 11`

**Comment by qzminski** [comment]
Hey @leofeyer do you mind checking if 88d183a works for you? I would fix the unit tests afterwards.

**Comment by leofeyer** [comment]
Yes, it works. 👍
