### ISSUE TITLE
[Question] Trailing slash policy

### ISSUE THREAD

**Issue by akroii** [terminal42/contao-url-rewrite#12]
It is possible to add an option for dealing with trailing slashes?

**Comment by Toflar** [comment]
We rely on Symfony routing under the hood so the way this is handled is the following: https://symfony.com/doc/current/routing.html#redirecting-urls-with-trailing-slashes

**Comment by Toflar** [comment]
In other words: The trailing slash is handled the same as the non-trailing slash.
