### ISSUE TITLE
Import feature

### ISSUE THREAD

**Issue by dmolineus** [terminal42/contao-url-rewrite#13]
For a project I need the possibility to import rewrite rules from a file (very likely csv). I'm thinking about implementing a custom config provider for it or contribute an import feature. Would you accept the last as an PR?

**Comment by Toflar** [comment]
Hmmm...why do you need an import? Do they have to be updated by the user? I mean, do they even need to be shown in the back end? Which Contao version are you going to work with?

**Comment by dmolineus** [comment]
> Hmmm...why do you need an import? Do they have to be updated by the user? 

What customer wants the ability to regularly update defined rewrite rules. The admin shouldn't have to be involved all the time

> I mean, do they even need to be shown in the back end? 

There are two use case scenarios:
 - Rewrite rules are visible in the backend and could be edited/managed here (prefered by the customer). Then I would need to implement an import 
 - All rules are only in a text file which are loaded by a custom config provider.

> Which Contao version are you going to work with?

Contao >= 4.7.

If you think an import feature would be useful I'm happy to provide a PR. If not, also fine. Totally understand if you plan to keep your extension in a manageable size.

**Comment by Toflar** [comment]
Yeah I just wonder if you'd be better off just writing your own `router` as in Contao 4.7 we now use the Symfony CMF `ChainRouter`. So it should be as easy as to tag a service that returns your custom route collection based on your file. It's probably easier than to write an import.
Yet still, I'm open to import/export features, just not sure about the best format.

**Comment by dmolineus** [comment]
I'm closing this issue. Resolved with a custom script and won't have any budget working on a generic import right now.
