### ISSUE TITLE
Internal rewrite instead of simple redirect?

### ISSUE THREAD

**Issue by stefanschleich** [terminal42/contao-url-rewrite#18]
Is it correct that this extension does not rewrite URLs but simply redirects from one to another? 

In my case I want to show the content of one url under another. For example if the user requests `domain.tld/foo/bar` I want to show the content of `domain.tld/foo?bar=1`. Current behaviour is that the request get's redirected to the new URL and it is visible to the user in the address bar.

Am I missing something?

**Comment by Toflar** [comment]
Yes, it redirects.

**Comment by stefanschleich** [comment]
Ok, so the name of the extension is a bit misleading for users looking for a way to rewrite URLs. Thanks for clearing this up.
