### ISSUE TITLE
Sf5 dependencies

### ISSUE THREAD

**Issue by m-vo** [terminal42/contao-url-rewrite#23]
This bundle currently has two things preventing it to run in a Sf5 environment:

First, the EL constraint `"symfony/expression-language": "^3.3 || ^4.0"`. I'm not sure this peer dependency is really needed. :thinking: There is no usage of the EL directly in code, so maybe it could be dropped completely. Otherwise it would need to be widened to `|| ^5.0`. 

Then there is a dependency on `haste` which brings `contao-community-alliance/composer-plugin` as a transitive dependency (which requires Sf 4 components at max). While this can all be fixed in the sub packages, `haste` is still only used at one place to for the DCA 'eye toggle button'. Maybe it would be better to inline this functionality instead of requiring the whole package. :upside_down_face:

**Comment by m-vo** [comment]
btw. :I'd really like to see this toggle feature / DX improvement in the core at one point.

**Comment by ameotoko** [comment]
There's more – see https://github.com/contao/contao/issues/2844#issuecomment-790986503

**Comment by m-vo** [comment]
These are two different things. :upside_down_face: 

This issue is about current (and correct) requirements, yours is about a bug happening in the `Configuration`. It would probably be best to open up a second issue.

**Comment by richardhj** [comment]
AFAICS the composer-plugin was updated for Symfony 5.
Plus, I second your opinion about the toggle button 😸

**Comment by fritzmg** [comment]
Regarding the toggle button: that should be added to the core :)
