### ISSUE TITLE
Issue with |urlattr 

### ISSUE THREAD

**Issue by Tastaturberuf** [terminal42/contao-url-rewrite#28]
Unter Contao 4.9.20 wird das ` |urlattr` automatisch an den Inserttag gehängt. Ich vermute dadurch dass es nur ein Teil einer Url ist, wird das jetzt nicht mehr richtig aufgelöst. Unter 4.9.16 lief das noch.

*Antwort-URL:*

Contao 4.9.16: `https://contao.local/gm/{{anystores_detail::{store_id}:alias}}.html` =>
`https://contao.local/gm/mein_alias_von_store_id.html`

Contao 4.9.20: `https://contao.local/gm/{{anystores_detail::{store_id}:alias|urlattr}}.html` => `https://contao.local/gm/%7B%7Banystores_detail::%7Bstore_id&#125;:alias|urlattr}}.html`

Kann ich irgendwie verhindern das `|urlattr` automatisch angehängt wird?

**Comment by Tastaturberuf** [comment]
Das hat unter Umständen nicht mit dem `|urlattr` zu tun, hab es über die DB rausgeworfen. Ergebnis: `https://contao.local/gm/%7B%7Banystores_detail::%7Bstore_id&#125;:alias}}.html`

**Comment by ausi** [comment]
`{{anystores_detail::{store_id}:alias}}` ist kein valider Insert-Tag, die Zeichen `{` und `}` dürfen darin nicht vorkommen. Was genau ist dieses `{store_id}`?

**Comment by Tastaturberuf** [comment]
Das ist Teil dieses Bundles hier und ist ein URL-Fragment(?).

**Comment by Tastaturberuf** [comment]
Wie gesagt, unter 4.9.16 läuft das noch.

**Comment by ausi** [comment]
> Das ist Teil dieses Bundles hier

Dann sollte das Feld denke ich nicht `rgxp => url` nutzen, da die URL erst durch ersetzen der `{store_id}` platzhalter zusammengebaut wird.

**Comment by Tastaturberuf** [comment]
OK, das funktioniert. Ich kann das in meiner Installation über den DCA fixen. Ich weiß nicht viele noch eine Inserttags zusammenbauen wollen und auch in das Problem schlittern. Könnte nen known issue sein.

**Comment by rabauss** [comment]
Should be fixed with https://github.com/contao/contao/pull/3407

**Comment by aschempp** [comment]
also fixed by https://github.com/terminal42/contao-url-rewrite/commit/c33914242344070c55d41fc3165293798aa07ddb I would say
