### ISSUE TITLE
Host-Limiting issue

### ISSUE THREAD

**Issue by IIM-Andreas** [terminal42/contao-url-rewrite#30]
Hi I have an issue with defining the domain.tld in the Host field.
Example: When I create a 301 redirect and set blub.net as host, then the redirect only works when I open https://blub.net/something. But I would like it to work with subdomains too, like https://www.blub.net/something or https://power.blub.net/something. How do I do this? *.blub.net also doesn't work. The check there seems to be exact instead of contains.

Do you have any suggestions?

**Comment by fritzmg** [comment]
Something like

```
condition: "request.host.matches('^(.*\.)?example\.com')"
```

should work. Not sure `request.host` is correct though, may be it needs to be `context.getHost()` instead.

**Comment by fritzmg** [comment]
> But it's still a little bit complicated for a normal user.

Any more complex requirement will be more complex to implement ;). A "normal" user can just add all the necessary domain.

**Comment by IIM-Andreas** [comment]
That's true, thanks for the fast support.
