### ISSUE TITLE
Installation with Manager (C4.9.41) stops

### ISSUE THREAD

**Issue by pixlemedia** [terminal42/contao-url-rewrite#41]
I`ve tried to install the latest version 1.72 but contao manager aborts installation:

composer update terminal42/contao-url-rewrite contao/conflicts --no-install
> Resolving dependencies using Composer Cloud v3.6.0-1-g9d9036c
[6.6MiB/0.20s] Loading composer repositories with package information
[64.6MiB/7.54s] Updating dependencies
[82.2MiB/7.80s] Your requirements could not be resolved to an installable set of packages.
[82.2MiB/7.81s] 

Problem 1
- Root composer.json requires terminal42/contao-url-rewrite ^1.7 -> satisfiable by terminal42/contao-url-rewrite[1.7.0, 1.7.1, 1.7.2].
- terminal42/contao-url-rewrite[1.7.0, ..., 1.7.2] require contao/core-bundle ^4.13 || ^5.0 -> found contao/core-bundle[4.13.0, ..., 4.13.23, 5.0.0, ..., 5.1.6] but these were not loaded, likely because it conflicts with another require.
[82.2MiB/7.81s] <warning>Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.</warning>
[36.9MiB/7.83s] Memory usage: 36.85MB (peak: 183.03MB), time: 7.84s.
[36.9MiB/7.83s] Finished Composer Cloud resolving.

Would be great to know, how to fix this. Any ideas?

**Comment by Toflar** [comment]
You cannot install 1.7 as this is only for 4.13 and 5.0.
You can use 1.6 instead.

**Comment by pixlemedia** [comment]
Thanks for your support. I tried to follow your recommandation but:

`poser install
$ /Applications/MAMP/bin/php/php7.4.33/bin/php -q -dmax_execution_time=0 -dmemory_limit=-1 -ddisplay_errors=0 -ddisplay_startup_errors=0 -derror_reporting=0 -dallow_url_fopen=1 -ddisable_functions= -ddate.timezone=Europe/Berlin /Users/bjarnerubin/Sites/localhost2/nissen-massivhaus.de/webseiten/web/contao-manager.phar.php composer install --no-dev --no-progress --no-ansi --no-interaction --optimize-autoloader
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Package operations: 3 installs, 0 updates, 0 removals
  - Downloading contao-community-alliance/composer-plugin (3.2.2)
  - Downloading codefog/contao-haste (4.25.25)
  - Downloading terminal42/contao-url-rewrite (1.6.0)
  - Installing contao-community-alliance/composer-plugin (3.2.2): Extracting archive
  - Installing codefog/contao-haste (4.25.25): Extracting archive
  - Installing terminal42/contao-url-rewrite (1.6.0): Extracting archive
Package contao-components/highlight is abandoned, you should avoid using it. No replacement was suggested.
Package lexik/maintenance-bundle is abandoned, you should avoid using it. No replacement was suggested.
Package patchwork/utf8 is abandoned, you should avoid using it. Use symfony/polyfill-mbstring or symfony/string instead.
Package swiftmailer/swiftmailer is abandoned, you should avoid using it. Use symfony/mailer instead.
Package symfony/debug is abandoned, you should avoid using it. Use symfony/error-handler instead.
Package symfony/swiftmailer-bundle is abandoned, you should avoid using it. Use symfony/mailer instead.
Package true/punycode is abandoned, you should avoid using it. No replacement was suggested.
Package webmozart/path-util is abandoned, you should avoid using it. Use symfony/filesystem instead.
Generating optimized autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
contao/manager-plugin: Dumping generated plugins file...
contao/manager-plugin: ...done dumping generated plugins file
Class Contao\ManagerPlugin\PluginLoader located in ./vendor/contao/manager-plugin/src/Resources/PluginLoader.php does not comply with psr-4 autoloading standard. Skipping.
101 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication
Added the web/preview.php file.
Added the web/app.php file.
Added the web/index.php file.
 // Clearing the cache for the prod environment with debug                      
 // false                                                                       
 [OK] Cache for the "prod" environment (debug=false) was successfully cleared.  
 // Clearing the cache for the dev environment with debug                       
 // true                                                                        
 [OK] Cache for the "dev" environment (debug=true) was successfully cleared.    
 // Warming up the cache for the prod environment with debug                    
 // false                                                                       
16:38:32 CRITICAL  [console] Error thrown while running command "cache:warmup --env=prod --no-ansi". Message: "Cannot call constructor" ["exception" => Error { …},"command" => "cache:warmup --env=prod --no-ansi","message" => "Cannot call constructor"]
In UrlRewriteLoader.php line 42:
                           
  Cannot call constructor  
                           
cache:warmup [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--] <command>
Script Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication handling the post-install-cmd event terminated with an exception
In ScriptHandler.php line 97:
                                                                               
  An error occurred while executing the "cache:warmup" command: 16:38:32 CRIT  
  ICAL  [console] Error thrown while running command "cache:warmup --env=prod  
   --no-ansi". Message: "Cannot call constructor" ["exception" => Error { …},  
  "command" => "cache:warmup --env=prod --no-ansi","message" => "Cannot call   
  constructor"]                                                                
                                                                               
  In UrlRewriteLoader.php line 42:                                             
                                                                               
    Cannot call constructor                                                    
                                                                               
                                                                               
  cache:warmup [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--  
  verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--en  
  v ENV] [--] <command>                                                        
                                                                               
install [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--dry-run] [--dev] [--no-suggest] [--no-dev] [--no-autoloader] [--no-progress] [--no-install] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--] [<packages>...]
# Process terminated with exit code 1
# Result: General error`

**Comment by Toflar** [comment]
Why are you installing 1.6.0 and not 1.6.6? Just use `^1.6` instead of `^1.7` and you should be good :)

**Comment by pixlemedia** [comment]
Legitimate question ;) latest 1.6 verion works just fine, thanks alot!
Handling looks advanced at first glance. I just like to use your extension to remove WWW if entered because my htaccess does not follow my rules given;) Can you shorty explain what to do in order to fit my needs?

**Comment by Toflar** [comment]
I wouldn't use that bundle for that, it makes no sense. Feel free to use any of the community support options - I'm sure you'll get help regarding your `.htaccess` as well :) https://to.contao.org/support
